export const workshops: TagTranslation[] = [
    { en: "Tantra", de: "Tantra", nl: "Tantra" },
    { en: "Family Constellations", de: "Familienaufstellung", nl: "Familieopstellingen" },
    { en: "Men's Workshops", de: "Männer-Workshops", nl: "Mannen Workshops" },
    { en: "Women's Workshops", de: "Frauen-Workshops", nl: "Vrouwen workshops" },
    { en: "Cuddle Workshops", de: "Kuschel-Workshops", nl: "Knuffelworkshops" },
    { en: "Bodywork", de: "Körperarbeit", nl: "Lichaamswerk" },
    { en: "Men's Circles", de: "Männerkreise", nl: "Mannencirkels" },
    { en: "Women's Circles", de: "Frauenkreise", nl: "Vrouwencirkels" },
    { en: "Healing", de: "Heilung", nl: "Healing" },
    { en: "Sound Healing", de: "Klangheilung", nl: "Soundhealing" },
    { en: "Breath", de: "Atem", nl: "Adem" },
    { en: "Yoga", de: "Yoga", nl: "Yoga" },
    { en: "Meditation", de: "Meditation", nl: "Meditatie" },
    { en: "Creativity", de: "Kreativität", nl: "Creativiteit" },
    { en: "Massage", de: "Massage", nl: "Massage" },
    { en: "Nature", de: "Natur", nl: "Natuur" },
    { en: "Shamanism", de: "Schamanismus", nl: "Sjamanisme" },
    { en: "Kundalini", de: "Kundalini", nl: "Kundalini" },
    { en: "Lightwork", de: "Lichtarbeit", nl: "Lichtwerk" },
    { en: "Energy Work", de: "Energiearbeit", nl: "Energiewerk" },
    { en: "Relationships", de: "Beziehungen", nl: "Relaties" },
    { en: "Entrepreneurship", de: "Unternehmertum", nl: "Ondernemen" },
    { en: "Personal Leadership", de: "Persönliche Führung", nl: "Persoonlijk Leiderschap" },
    { en: "The Inner Voice", de: "Die Stimme von innen", nl: "De stem van binnenuit" },
    { en: "Therapy", de: "Therapie", nl: "Therapie" },
    { en: "Collective Evolution", de: "Kollektive Evolution", nl: "Collectieve Evolutie" },
    { en: "Ice Bath", de: "Eisbad", nl: "Ijsbad" },
    { en: "Anger Work", de: "Wutarbeit", nl: "Anger work" },
    { en: "Systemic Work", de: "Systemische Arbeit", nl: "Systemisch werk" },
    { en: "Conscious Sexuality", de: "Bewusste Sexualität", nl: "Conscious Sexuality" },
    { en: "Touch", de: "Berührung", nl: "Aanraking" },
    { en: "Inner Child", de: "Inneres Kind", nl: "Innerlijk Kind" },
    { en: "Authentic Relating", de: "Authentic Relating", nl: "Authentic Relating" },
    { en: "Playfulness", de: "Verspieltheit", nl: "Playfulness" },
    { en: "Shibari", de: "Shibari", nl: "Shibari" },
    { en: "Horses", de: "Pferde", nl: "Paarden" },
    { en: "Sharing Circle", de: "Sharing-Kreis", nl: "Sharing Circle" },
    { en: "Forest Bathing (Shinrin Yoku)", de: "Waldbaden (Shinrin Yoku)", nl: "Bosbad -Shinrin Yoku" },
    { en: "Ayurveda", de: "Ayurveda", nl: "Ayurveda" },
    { en: "Satsang", de: "Satsang", nl: "Satsang" },
    { en: "Knowledge", de: "Wissen", nl: "Kennis" },
    { en: "Gemstones", de: "Edelsteine", nl: "Edelstenen" },
    { en: "Year Program", de: "Jahrestraining", nl: "Jaartraject" },
    { en: "A Course in Miracles", de: "Ein Kurs in Wundern", nl: "Een cursus in wonderen" },
    { en: "Mediumship", de: "Medialität", nl: "Mediumschap" },
    { en: "Human Design", de: "Human Design", nl: "Human design" },
    { en: "Qi Gong", de: "Qi Gong", nl: "Qi Gong" },
    { en: "Consciousness Development", de: "Bewusstseinsentwicklung", nl: "Bewustzijnsontwikkeling" },
    { en: "Embodiment", de: "Embodiment", nl: "Embodiment" },
    { en: "Health", de: "Gesundheit", nl: "Gezondheid" },
    { en: "Forest Bathing", de: "Waldbaden", nl: "Bosbaden" },
    { en: "Reiki", de: "Reiki", nl: "Reiki" },
    { en: "Aura Reading", de: "Aura-Reading", nl: "Aura reading" },
    { en: "Tarot", de: "Tarot", nl: "Tarot" },
    { en: "Wim Hof Method", de: "Wim-Hof-Methode", nl: "Wim Hof Method" },
    { en: "Breathwork", de: "Atemarbeit", nl: "Ademwerk" },
    { en: "Temple", de: "Tempel", nl: "Tempel" },
    { en: "Connection", de: "Verbindung", nl: "Verbinding" },
    { en: "Sensuality", de: "Sinnlichkeit", nl: "Sensualiteit" },
    { en: "Herbs", de: "Kräuter", nl: "Kruiden" },
    { en: "Personal Development", de: "Persönliche Entwicklung", nl: "Persoonlijke Ontwikkeling" },
    { en: "Shadow Work", de: "Schattenarbeit", nl: "Schaduwwerk" },
    { en: "Kundalini Activation", de: "Kundalini-Aktivierung", nl: "Kundalini activatie" },
    { en: "Chakras", de: "Chakren", nl: "Chakra's" },
    { en: "Love", de: "Liebe", nl: "Liefde" },
    { en: "Heart Connection", de: "Herzverbindung", nl: "Hartsverbinding" },
    { en: "Astrology", de: "Astrologie", nl: "Astrologie" },
    { en: "Dating", de: "Dating", nl: "Dating" },
    { en: "Nonduality", de: "Non-Dualität", nl: "Non-dualiteit" },
    { en: "Being Orientation", de: "Seinsorientierung", nl: "Zijnsoriëntatie" },
    { en: "Tai Chi / Tai Ji", de: "Tai Chi / Taiji", nl: "Tai chi / Tai ji" },
    { en: "Animals", de: "Tiere", nl: "Dieren" },
    { en: "Course", de: "Kurs", nl: "Cursus" },
    { en: "Nonviolent Communication", de: "Gewaltfreie Kommunikation", nl: "Geweldloze Communicatie" },
    { en: "Boundaries", de: "Grenzen", nl: "Grenzen" },
    { en: "Children's Workshop", de: "Kinderworkshop", nl: "Kinderworkshop" },
    { en: "Sailing", de: "Segeln", nl: "Zeilen" },
    { en: "Acro Yoga", de: "Acro Yoga", nl: "Acro Yoga" },
    { en: "Conscious Parenting", de: "Bewusste Elternschaft", nl: "Bewust Ouderschap" },
    { en: "Hypnosis", de: "Hypnose", nl: "Hypnose" },
    { en: "Constellations", de: "Aufstellungen", nl: "Opstellingen" },
    { en: "Cosmic Contact", de: "Kosmischer Kontakt", nl: "Kosmisch Contact" },
    { en: "Haptonomy", de: "Haptonomie", nl: "Haptonomie" },
    { en: "Sacred Sexuality", de: "Heilige Sexualität", nl: "Sacred Sexuality" },
    { en: "Aromatherapy", de: "Aromatherapie", nl: "Aromatherapie" },
    { en: "Mindfulness", de: "Achtsamkeit", nl: "Mindfulness" },
    { en: "Pregnancy", de: "Schwangerschaft", nl: "Zwangerschap" },
    { en: "Taoism", de: "Taoismus", nl: "Taoïsme" },
    { en: "Alchemy", de: "Alchemie", nl: "Alchemie" },
    { en: "Transformational Sexuality", de: "Transformative Sexualität", nl: "Transformatieseksualiteit" },
    { en: "Multidimensional Embodiment Transmission", de: "Multidimensionale Embodiment-Transmission", nl: "Multidimensional Embodiment Transmission" },
    { en: "Multidimensionality", de: "Multidimensionalität", nl: "Multidimensionaliteit" },
    { en: "Martial Arts", de: "Kampfkünste", nl: "Martial Arts" },
    { en: "Kung Fu", de: "Kung Fu", nl: "Kung Fu" },
    { en: "Poetry", de: "Poesie", nl: "Poëzie" },
    { en: "Past Life Regression", de: "Rückführung in frühere Leben", nl: "Past Life Regression" },
    { en: "Soul Voice", de: "Seelenstimme", nl: "Soul Voice" },
    { en: "Postpartum", de: "Wochenbett", nl: "Postpartum" },
    { en: "Motherhood", de: "Mutterschaft", nl: "Moederschap" },
    { en: "Fatherhood", de: "Vaterschaft", nl: "Vaderschap" },
    { en: "Open Relationships", de: "Offene Beziehungen", nl: "Open Relaties" },
    { en: "Talent Game", de: "Talentenspiel", nl: "Talentenspel" },
    { en: "Numerology", de: "Numerologie", nl: "Numerologie" },
    { en: "Mother Circle", de: "Mutterkreis", nl: "Moedercirkel" },
    { en: "Relaxation", de: "Entspannung", nl: "Ontspanning" },
    { en: "Somatic Experiencing", de: "Somatic Experiencing", nl: "Somatic Experiencing" },
    { en: "New Earth", de: "Neue Erde", nl: "Nieuwe Aarde" },
    { en: "Manifestation", de: "Manifestieren", nl: "Manifesteren" },
    { en: "Quantum Jumping", de: "Quantum Jumping", nl: "Quantum Jumping" },
    { en: "Law of Attraction", de: "Gesetz der Anziehung", nl: "Wet van de Aantrekkingskracht" },
    { en: "Soul Happiness", de: "Seelenglück", nl: "Zielsgeluk" },
    { en: "Channeling", de: "Channeling", nl: "Channeling" },
    { en: "Grief and Loss", de: "Trauer und Verlust", nl: "Rouw en Verlies" },
    { en: "Feng Shui", de: "Feng Shui", nl: "Feng Shui" },
    { en: "Christmas", de: "Weihnachten", nl: "Kerst" },
    { en: "Psychology", de: "Psychologie", nl: "Psychologie" },
    { en: "Mother-Daughter", de: "Mutter-Tochter", nl: "Moeder-dochter" },
    { en: "Father-Son", de: "Vater-Sohn", nl: "Vader-zoon" },
    { en: "Drum Making", de: "Trommelbau", nl: "Drum Maken" },
    { en: "Self-Sufficient Living", de: "Autarkes Leben", nl: "Zelfvoorzienend Leven" },
    { en: "Make Something Yourself", de: "Selbst etwas herstellen", nl: "Zelf iets maken" },
    { en: "Hiking", de: "Wandern", nl: "Wandelen" },
    { en: "Writing", de: "Schreiben", nl: "Schrijven" },
    { en: "Trauma Release", de: "Traumalösung", nl: "Trauma Release" },
    { en: "Universal Oneness", de: "Universelle Einheit", nl: "Universele Eenheid" },
    { en: "Children's Yoga", de: "Kinderyoga", nl: "Kinderyoga" },
    { en: "Sufism", de: "Sufismus", nl: "Soefisme" },
    { en: "Body Awareness", de: "Körperbewusstsein", nl: "Lichaamsbewustzijn" },
    { en: "Soul Connection", de: "Seelenverbindung", nl: "Zielsverbinding" },
    { en: "Addiction", de: "Sucht", nl: "Verslaving" },
    { en: "Psychiatric Labels", de: "Psychische Labels", nl: "Psychische Labels" },
    { en: "Self-Love", de: "Selbstliebe", nl: "Zelfliefde" },
    { en: "Parent-Child", de: "Eltern-Kind", nl: "Ouder-kind" },
    { en: "Germanic New Medicine", de: "Germanische Heilkunde", nl: "Germaanse Geneeskunde" },
    { en: "Art", de: "Kunst", nl: "Kunst" },
    { en: "Father-Daughter", de: "Vater-Tochter", nl: "Vader-dochter" },
    { en: "Intuitive Painting", de: "Intuitives Malen", nl: "Intuïtief Schilderen" },
    { en: "Self-Expression", de: "Selbstausdruck", nl: "Zelfexpressie" },
    { en: "Sexuality", de: "Sexualität", nl: "Seksualiteit" },
    { en: "Intuition", de: "Intuition", nl: "Intuïtie" },
    { en: "Card Readings", de: "Kartenlegungen", nl: "Kaartleggingen" },
    { en: "Vanishing Twin", de: "Alleingeborener Zwilling", nl: "Alleen Geboren Tweeling" },
    { en: "Primal Movement", de: "Primal Movement", nl: "Primal Movement" },
    { en: "Jewelry Making", de: "Schmuck herstellen", nl: "Sieraden Maken" },
    { en: "Menopause / Transition", de: "Menopause / Wechseljahre", nl: "Menopauze / Overgang" },
    { en: "Meet Your Guides", de: "Triff deine Guides", nl: "Ontmoet je Gidsen" },
    { en: "Shiatsu", de: "Shiatsu", nl: "Shiatsu" },
    { en: "HSP (Highly Sensitive Person)", de: "HSP (Hochsensible Person)", nl: "HSP" },
    { en: "Yoni Steam", de: "Yoni-Dampfbad", nl: "Yoni Steam" },
    { en: "Emotion Coaching", de: "Emotionscoaching", nl: "Emotiecoaching" },
    { en: "Family System", de: "Familiensystem", nl: "Familiesysteem" },
    { en: "Laughter Workshop", de: "Lachworkshop", nl: "Lachworkshop" },
    { en: "Stress", de: "Stress", nl: "Stress" },
    { en: "Focusing", de: "Focusing", nl: "Focusing" },
    { en: "Double Portrait", de: "Doppelporträt", nl: "Dubbelportret" },
    { en: "Children's Dance", de: "Kindertanz", nl: "Kinderdans" },
    { en: "Program", de: "Programm", nl: "Traject" },
    { en: "SUP Yoga", de: "SUP-Yoga", nl: "Supyoga" },
    { en: "Gifted", de: "Hochbegabt", nl: "Hoogbegaafd" },
    { en: "Co-creation", de: "Co-Kreation", nl: "Co-creatie" },
    { en: "Family", de: "Familie", nl: "Gezin/Familie" },
    { en: "Self-care", de: "Selbstfürsorge", nl: "Zelfzorg" },
    { en: "Yogadanza", de: "Yogadanza", nl: "Yogadanza" },
    { en: "Intimacy", de: "Intimität", nl: "Intimiteit" },
    { en: "Highly Sensitive", de: "Hochsensibel", nl: "Hoogsensitief" },
    { en: "Yoga Nidra", de: "Yoga Nidra", nl: "Yoga Nidra" },
    { en: "Mixed Circle", de: "Gemischter Kreis", nl: "Gemengde Cirkel" },
    { en: "Kundalini Yoga", de: "Kundalini Yoga", nl: "Kundalini Yoga" },
    { en: "Mother Earth", de: "Mutter Erde", nl: "Moeder Aarde" },
    { en: "Insight Dialogue", de: "Insight Dialogue", nl: "Insight Dialogue" },
    { en: "Pendulum Dowsing", de: "Pendeln", nl: "Pendelen" },
    { en: "Medicine Wheel", de: "Medizinrad", nl: "Medicijnwiel" },
    { en: "Sauna", de: "Sauna", nl: "Sauna" },
    { en: "Queer", de: "Queer", nl: "Queer" },
    { en: "Dreams", de: "Träume", nl: "Dromen" },
    { en: "Rebirthing", de: "Rebirthing", nl: "Rebirthing" },
    { en: "Pilates", de: "Pilates", nl: "Pilates" },
    { en: "Tzolkin / Maya Calendar", de: "Tzolkin / Maya-Kalender", nl: "Tzolkin / Mayakalender" },
    { en: "Cooking", de: "Kochen", nl: "Koken" },
    { en: "Foraging", de: "Wildkräutersammeln", nl: "Wildplukken" },
    { en: "Herbalism", de: "Kräuterkunde", nl: "Kruidenleer" },
    { en: "Feminine", de: "Weiblichkeit", nl: "Feminine" },
    { en: "Masculine", de: "Männlichkeit", nl: "Masculine" },
    { en: "Osho", de: "Osho", nl: "Osho" },
    { en: "Creative Arts Therapy", de: "Kreativtherapie", nl: "Vaktherapie" },
    { en: "Drama Therapy", de: "Dramatherapie", nl: "Dramatherapie" },
    { en: "Polyvagal Theory", de: "Polyvagal-Theorie", nl: "Polyvagaal Theorie" },
    { en: "Power Place", de: "Kraftort", nl: "Krachtplek" },
    { en: "Labyrinth", de: "Labyrinth", nl: "Labyrint" },
    { en: "Organizational Constellations", de: "Organisationsaufstellungen", nl: "Organisatieopstellingen" },
    { en: "Relationship Constellations", de: "Beziehungsaufstellungen", nl: "Relatieopstellingen" },
    { en: "Work and Career", de: "Arbeit und Karriere", nl: "Werk en Loopbaan" },
    { en: "Surfing", de: "Surfen", nl: "Surfen" },
    { en: "Fasting", de: "Fasten", nl: "Vasten" },
    { en: "Gene Keys", de: "Gene Keys", nl: "Gene Keys" },
    { en: "Soul Mission", de: "Seelenmission", nl: "Zielsmissie" }
];

export const ceremonies: TagTranslation[] = [
    { en: "Sweat Lodge", de: "Schwitzhütte", nl: "Zweethut" },
    { en: "Cacao Ceremony", de: "Kakaozeremonie", nl: "Cacao ceremonie" },
    { en: "Initiations", de: "Einweihungen", nl: "Inwijdingen" },
    { en: "New Year's Eve", de: "Silvester", nl: "Oud & Nieuw" },
    { en: "Plant Medicine", de: "Pflanzenmedizin", nl: "Plantmedicijn" },
    { en: "Ritual", de: "Ritual", nl: "Ritueel" },
    { en: "Breath Circle", de: "Atemkreis", nl: "Ademcirkel" },
    { en: "Detox", de: "Detox", nl: "Detox" },
    { en: "Truffle Ceremony", de: "Trüffelzeremonie", nl: "Truffel Ceremonie" },
    { en: "Water Ceremony", de: "Wasserzeremonie", nl: "Water ceremonie" },
    { en: "Fire Ceremony", de: "Feuerzeremonie", nl: "Vuur Ceremonie" },
    { en: "Vision Quest", de: "Visionssuche", nl: "Vision Quest" },
    { en: "Sound Journey / Sound Bath", de: "Klangreise / Sound Bath", nl: "Klankreis-Soundbath" },
    { en: "Kambo", de: "Kambo", nl: "Kambo" },
    { en: "New Moon", de: "Neumond", nl: "New Moon" },
    { en: "Full Moon", de: "Vollmond", nl: "Full Moon" },
    { en: "Rapé", de: "Rapé", nl: "Rapé" },
    { en: "Inner Journey", de: "Innere Reise", nl: "Innerlijke Reis" },
    { en: "Tea Ceremony", de: "Teezeremonie", nl: "Thee Ceremonie" },
    { en: "Rite of the Womb", de: "Rite of the Womb", nl: "Rite of the Womb" },
    { en: "Light Language", de: "Lichtsprache", nl: "Lichttaal" },
    { en: "Medicine Walk", de: "Medizinspaziergang", nl: "Medicijnwandeling" },
    { en: "Equinox/Solstice", de: "Tagundnachtgleiche/Sonnenwende", nl: "Equinox/Zonnewende" },
    { en: "Firewalk", de: "Feuerlauf", nl: "Vuurloop" },
    { en: "Trance Journey", de: "Trancereise", nl: "Trancereis" },
    { en: "Blue Lotus", de: "Blaue Lotus", nl: "Blauwe Lotus" },
    { en: "Rites of Passage", de: "Riten des Übergangs", nl: "Rites of Passage" },
    { en: "Soul Retrieval", de: "Seelenrückholung", nl: "Soul Retrieval" },
    { en: "Celtic Year Festivals", de: "Keltische Jahresfeste", nl: "Keltische Jaarfeesten" },
    { en: "Womb Healing", de: "Womb Healing", nl: "Womb Healing" },
    { en: "Despacho Ceremony", de: "Despacho-Zeremonie", nl: "Despacho Ceremonie" }
];

export const dance: TagTranslation[] = [
    { en: "Ecstatic Dance", de: "Ecstatic Dance", nl: "Ecstatic Dance" },
    { en: "Tantric Dance", de: "Tantrischer Tanz", nl: "Tantric Dance" },
    { en: "Biodanza", de: "Biodanza", nl: "Biodanza" },
    { en: "Trance Dance", de: "Trance Dance", nl: "Trance Dance" },
    { en: "Shamanic Dance", de: "Schamanischer Tanz", nl: "Shamanic dance" },
    { en: "5Rhythms", de: "5 Rhythmen", nl: "5 Ritmes" },
    { en: "Intuitive Dance", de: "Intuitiver Tanz", nl: "Intuitive Dance" },
    { en: "Free Dance", de: "Freier Tanz", nl: "Vrije Dans" },
    { en: "Contact Improvisation", de: "Kontaktimprovisation", nl: "Contact Improvisatie" },
    { en: "Somatic Dance", de: "Somatischer Tanz", nl: "Somatic Dance" },
    { en: "Dancing in Connection", de: "Tanzen in Verbindung", nl: "Dansen in verbinding" },
    { en: "Ritual Dance", de: "Ritueller Tanz", nl: "Ritual Dance" },
    { en: "Dance Meditation", de: "Tanzmeditation", nl: "Dansmeditatie" },
    { en: "Open Floor", de: "Open Floor", nl: "Open Floor" },
    { en: "Conscious Dance", de: "Conscious Dance", nl: "Conscious Dance" },
    { en: "Dance Improvisation", de: "Tanzimprovisation", nl: "Dansimprovisatie" },
    { en: "Balfolk", de: "Balfolk", nl: "Balfolk" },
    { en: "Systemic Dance", de: "Systemischer Tanz", nl: "Systemic Dance" },
    { en: "Haka", de: "Haka", nl: "Haka" },
    { en: "Latin Dance", de: "Latin Dance", nl: "Latin Dance" },
    { en: "Zouk", de: "Zouk", nl: "Zouk" },
    { en: "Sufi Dance", de: "Sufi-Tanz", nl: "Sufidans" },
    { en: "Dance Performance", de: "Tanzperformance", nl: "Dans Performance" },
    { en: "Whirling", de: "Wirbeln", nl: "Wervelen" },
    { en: "Dance Workshop", de: "Tanzworkshop", nl: "Dansworkshop" },
    { en: "Movement Medicine", de: "Movement Medicine", nl: "Movement Medicine" },
    { en: "Conscious Clubbing", de: "Conscious Clubbing", nl: "Conscious Clubbing" },
    { en: "Systemic Dance", de: "Systemischer Tanz", nl: "Systemische Dans" },
    { en: "Sensual Dance", de: "Sinnlicher Tanz", nl: "Sensuele Dans" },
    { en: "Bellydance", de: "Bauchtanz", nl: "Bellydance" },
    { en: "Dance Coaching", de: "Tanzcoaching", nl: "Danscoaching" },
    { en: "Sacred Dance", de: "Heiliger Tanz", nl: "Sacred Dance" },
    { en: "Embodiment Dance", de: "Embodiment Dance", nl: "Embodiment Dance" },
    { en: "Authentic Movement", de: "Authentic Movement", nl: "Authentic Movement" },
    { en: "Contact Beyond Contact", de: "Contact Beyond Contact", nl: "Contact Beyond Contact" },
    { en: "Outdoor Dance", de: "Tanz im Freien", nl: "Outdoor Dance" },
    { en: "Forró", de: "Forró", nl: "Forró" }
];

export const music: TagTranslation[] = [
    { en: "Mantra Singing", de: "Mantra singen", nl: "Mantra zingen" },
    { en: "Kirtan", de: "Kirtan", nl: "Kirtan" },
    { en: "Drum Circle", de: "Trommelkreis", nl: "Drumcirkel" },
    { en: "Voice Liberation", de: "Stimm-Befreiung", nl: "Stembevrijding" },
    { en: "Singing Bowls", de: "Klangschalen", nl: "Klankschalen" },
    { en: "Sound Bath", de: "Klangbad", nl: "Klankbad" },
    { en: "Music Evening", de: "Musikabend", nl: "Muziekavond" },
    { en: "Live Music", de: "Livemusik", nl: "Live muziek" },
    { en: "Handpan", de: "Handpan", nl: "Handpan" },
    { en: "Performance", de: "Auftritt", nl: "Optreden" },
    { en: "Music Lesson", de: "Musikunterricht", nl: "Muziekles" },
    { en: "Sound Journey", de: "Klangreise", nl: "Klankreis" },
    { en: "Lying Concert", de: "Liegekonzert", nl: "Ligconcert" },
    { en: "Singing Circle", de: "Singkreis", nl: "Zangcirkel" },
    { en: "Voice Expression", de: "Stimmausdruck", nl: "Stemexpressie" },
    { en: "Music Therapy", de: "Musiktherapie", nl: "Muziektherapie" },
    { en: "Sanskrit Mantra Recitation", de: "Sanskrit-Mantrarezitation", nl: "Sanskriet Mantrarecitatie" },
    { en: "Ukulele", de: "Ukulele", nl: "Ukelele" },
    { en: "Didgeridoo", de: "Didgeridoo", nl: "Didgeridoo" },
    { en: "Harp", de: "Harfe", nl: "Harp" },
    { en: "Jam Session", de: "Jam-Session", nl: "Jamsessie" },
    { en: "Psy Trance", de: "Psy Trance", nl: "Psy Trance" }
];

export const festivalsAndRetreats: TagTranslation[] = [
    { en: "Gatherings", de: "Zusammenkünfte", nl: "Gatherings" },
    { en: "Festivals", de: "Festivals", nl: "Festivals" },
    { en: "Multi-day Retreats", de: "Mehrtägige Retreats", nl: "Meerdaagse retraites" },
    { en: "Silent Retreat", de: "Schweigeretreat", nl: "Stilteretraite" },
    { en: "1-Day Retreat", de: "1-Tages-Retreat", nl: "1-Dags retraite" },
    { en: "Divine Living", de: "Divine Living", nl: "Divine Living" },
    { en: "1-on-1 Retreat", de: "1-zu-1-Retreat", nl: "Retraite 1-op-1" },
    { en: "Mini Retreat in Nature", de: "Mini-Retreat in der Natur", nl: "Mini retraite in de natuur" },
    { en: "Holiday", de: "Urlaub", nl: "Vakantie" },
    { en: "Fair", de: "Messe", nl: "Beurs" }
];

export const lecturesAndPerformances: TagTranslation[] = [
    { en: "Concert", de: "Konzert", nl: "Concert" },
    { en: "Book Presentation", de: "Buchpräsentation", nl: "Boekpresentatie" },
    { en: "Storytelling", de: "Storytelling", nl: "Storytelling" },
    { en: "Lecture", de: "Vortrag", nl: "Lezing" },
    { en: "Film", de: "Film", nl: "Film" },
    { en: "Theatre", de: "Theater", nl: "Theater" },
    { en: "Webinar", de: "Webinar", nl: "Webinar" },
    { en: "Cabaret", de: "Kabarett", nl: "Cabaret" },
    { en: "Show", de: "Vorstellung", nl: "Voorstelling" },
    { en: "Presentation", de: "Präsentation", nl: "Presentatie" },
    { en: "Experiential Lectures", de: "Erlebnisvorträge", nl: "Belevingslezingen" },
    { en: "Conference", de: "Kongress", nl: "Congres" }
];

export const allTags: TagTranslation[] = [
    ...workshops,
    ...ceremonies,
    ...dance,
    ...music,
    ...festivalsAndRetreats,
    ...lecturesAndPerformances
]

export const allTagsMap = new Map(allTags.map(tag => [tag.en, tag]));

export type TagTranslation = { en: string; de: string; nl: string };
